version: "3"

services:
  ifad-backend:
    image: nicholastmosher/ifad-backend:v0.2.2
    container_name: "ifad"
    environment:
      GENES_FILE: "/ifad/files/gene-types.txt"
      ANNOTATIONS_FILE: "/ifad/files/tair.gaf"
    ports:
      - 80:3000
    volumes:
      - "./assets:/ifad/files"
